import mongoose, { Types } from "mongoose";

const jobSchema=mongoose.Schema({
    title:{
        type:String,
        required:true
    },
    description:{
        type:String,
        required:true
    },
    salary:{
        type:Number,
        required:true
    },
    experience:{
        type:Number,
        required:true
    },
    requirements:[{
        type:String,
        required:true
    }],
    positions:{
        type:Number,
        required:true
    },
    jobType:{
        type:String,
        required:true
    },
    location:{
        type:String,
        required:true
    },
    company:{
        type:mongoose.Schema.Types.ObjectId,
        required:true,
        ref:'Company'
    },
    createdBy:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'Company',
        required:true
    },
    applications:[{
        type:mongoose.Schema.Types.ObjectId,
        ref:'Application'
    }]
},{timestamps:true})
export const Jobs=mongoose.model('Jobs',jobSchema)